name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * 5

jobs:
  unit-tests:
    name: Vim ${{ matrix.vim_version }} on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

        vim_version:
          - v9.1.0000
          - head

        download:
          - available

        include:
          - os: ubuntu-latest
            vim_version: head
            download: never

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      - name: Setup Vim
        id: vim
        uses: thinca/action-setup-vim@v2
        with:
          vim_version: ${{ matrix.vim_version }}
          download: ${{ matrix.download }}
      - name: Show Vim version
        run: |
          ${{ steps.vim.outputs.executable }} --version
      - name: Setup themis.vim
        uses: actions/checkout@v5
        with:
          repository: thinca/vim-themis
          path: themis
      - name: Run test
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: |
          ./themis/bin/themis --reporter tap
