name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * 5

jobs:
  vim-unit-tests:
    name: Vim ${{ matrix.vim_version }} on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

        vim_version:
          - v9.1.0000
          - head

        download:
          - available

        include:
          - os: ubuntu-latest
            vim_version: head
            download: never

    uses: mityu/workflow-run-vim-themis/.github/workflows/run-themis.yml@v20250912
    with:
      vim_type: vim
      vim_version: ${{ matrix.vim_version }}
      os: ${{ matrix.os }}
      download: ${{ matrix.download }}

  neovim-unit-tests:
    name: Neovim ${{ matrix.vim_version }} on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

        vim_version:
          - v0.11.0
          - head

        download:
          - available

        include:
          - os: ubuntu-latest
            vim_version: head
            download: never

    uses: mityu/workflow-run-vim-themis/.github/workflows/run-themis.yml@v20250912
    with:
      vim_type: neovim
      vim_version: ${{ matrix.vim_version }}
      os: ${{ matrix.os }}
      download: ${{ matrix.download }}
